### ISSUE TITLE
Evoke 2016

### ISSUE THREAD

**Issue by phaazon** [phaazon/spectra#1]
This issue is used to gather feedback about what was great and what was less great while writing my [evoke 2016](https://www.evoke.eu/2016) PC demo.
# What was great
- textures are easy to load using the [image](https://crates.io/image) crate ; however, we need to add a system (mpsc?) to implement some kind of progress bar.
- the time panel, very handy to skip / jump / synchronize.
# What was not great
- [x] I missed the logical synchronization code ; that is, being able to run some code for a given period of time and then switch to something else (maybe something FRP-ish?) (#4).
- [x] resource hot reloading was missing (#3).
- [ ] the time panel doesn’t show the current time, plus I needed fine grain control over the time (like being able to reduce the window time to move milliseconds by milliseconds) (#7).
- [x] I often wanted to switch from runtime camera to freefly camera (#5).
- [x] cannot write a progress bar code with the current `ion` codebase.
- [ ] a proper editor for the curves and animation (#6).
- [ ] keyframes editing: that was awful. I had to launch the demo in debug (i.e. with freefly camera support), set the camera’s transform, output it to stdout (via a keyboard shortcut), quit the demo, copy-paste the transform at the wished time, re-compile without the debug camera, and see whether it’s working and synced.
- [x] unused uniform semantics for debug purposes (~~phaazon/luminance-rs#14~~, ~~phaazon/luminance-rs#15~~).
